import { BasePerformanceReportingCSVExportRequest } from './basePerformanceReportingCSVExportRequest'

export interface PermitAlterationOutcomesCSVExportRequest extends BasePerformanceReportingCSVExportRequest {}
